apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bank-soft-mode-policy-axerated
  namespace: bank
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: bank
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: bank
